version: "3.3"

services:
  library_token_frontend:
    image: library_token_frontend
    container_name: library_token_frontend
    restart: always
    build:
        context: .
        dockerfile: Dockerfile.prod
    ports:
      - "7970:3000"
    env_file:
    - .env
    command: sh -c "cd /app && serve -s build"
    networks:
      - frontend_default

networks:
  frontend_default:
    external: true