version: "3.3"

services:
  library_token_frontend_test:
    image: library_token_frontend_test
    container_name: library_token_frontend_test
    restart: always
    build:
        context: .
        dockerfile: Dockerfile.test
    ports:
      - "7971:3000"
    env_file:
    - .env.test
    command: sh -c "cd /app && serve -s build"
    networks:
      - frontend_default

networks:
  frontend_default:
    external: true