version: "3.3"
services:
  library_token_backend_prod:
    container_name: library_token_backend_prod
    image: library_token_backend_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9574:3001"
    env_file:
      - .env
    networks:
      - library-token_backend_test
    depends_on:
      - redis_library_prod

  redis_library_prod:
    container_name: redis_library_prod
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data-library-prod:/data
    networks:
      - library-token_backend_test



networks:
  library-token_backend_test:
    external: true
volumes:
  redis-data-library-prod: 