name: Backend Deployment
on:
    workflow_dispatch:
    # push:
    #     paths:
    #         - "backend/**"
    #     branches:
    #         - "main"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Establish ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
            cd /webapps/test-servers/Library-Token-2025
            git fetch origin
            git checkout test
            git pull
            git status
            cd backend
            docker-compose -f docker-compose.prod.yml up -d --build
